# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AnalystService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AnalystService.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14\x41nalystService.proto\"\x18\n\x05\x45nter\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x05\n\x03Out2+\n\x0e\x41nalystService\x12\x19\n\x07\x41nalyse\x12\x06.Enter\x1a\x04.Out\"\x00\x62\x06proto3'
)




_ENTER = _descriptor.Descriptor(
  name='Enter',
  full_name='Enter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='Enter.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=48,
)


_OUT = _descriptor.Descriptor(
  name='Out',
  full_name='Out',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['Enter'] = _ENTER
DESCRIPTOR.message_types_by_name['Out'] = _OUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Enter = _reflection.GeneratedProtocolMessageType('Enter', (_message.Message,), {
  'DESCRIPTOR' : _ENTER,
  '__module__' : 'AnalystService_pb2'
  # @@protoc_insertion_point(class_scope:Enter)
  })
_sym_db.RegisterMessage(Enter)

Out = _reflection.GeneratedProtocolMessageType('Out', (_message.Message,), {
  'DESCRIPTOR' : _OUT,
  '__module__' : 'AnalystService_pb2'
  # @@protoc_insertion_point(class_scope:Out)
  })
_sym_db.RegisterMessage(Out)



_ANALYSTSERVICE = _descriptor.ServiceDescriptor(
  name='AnalystService',
  full_name='AnalystService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=57,
  serialized_end=100,
  methods=[
  _descriptor.MethodDescriptor(
    name='Analyse',
    full_name='AnalystService.Analyse',
    index=0,
    containing_service=None,
    input_type=_ENTER,
    output_type=_OUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANALYSTSERVICE)

DESCRIPTOR.services_by_name['AnalystService'] = _ANALYSTSERVICE

# @@protoc_insertion_point(module_scope)
